from . import college
from . import program
from . import batch
from . import plan_line
from . import student
from . import installment
from . import payment
from . import whatsapp
from . import reminder_log
from . import installment_notify
from . import res_config_settings
from . import dashboard
